language: pyhton

compiler:
    - gcc

os:
    - linux

branches:
    only:
        - master

before_install:
    - echo "before_install..."
    - git submodule update --init --recursive
    - git fetch --tags
    - sleep 1
    - git checkout $TRAVIS_BRANCH
    - export PROJECTGITVERSION=`git describe --tags --always |sed 's/^v//'`
    - echo $PROJECTGITVERSION
    - echo $TRAVIS_OS_NAME
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - export TRAVIS_TAG=`git describe --tags --exact-match HEAD 2>/dev/null`
    - echo $TRAVIS_TAG

install:
    - echo "install..."

script:
    - echo "script..."
    - export PACKAGENAME=pulsemodel_$PROJECTGITVERSION.zip
    - echo "Packaging sources of " $PACKAGENAME
    - pwd
    - ls
    
    - mkdir ../pulsemodel_$PROJECTGITVERSION
    - cp -r * ../pulsemodel_$PROJECTGITVERSION
    - rm -fr ../pulsemodel_$PROJECTGITVERSION/.git*
    - mv ../pulsemodel_$PROJECTGITVERSION .
    - zip -r $PACKAGENAME pulsemodel_$PROJECTGITVERSION
    - ls
    - ls -l $PACKAGENAME
    #- echo $TRAVIS_TAG

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VPuKCfzJEpnDb7fYyaGKYWKx+XSwDvo6sbgwJGqDhGINWJ3jYm3s5C22xeujlfzjczlsCvM2ENNQLXIu8X3q/LkFyPM3pJMCvfPgiHu5KBZmrEn+/O4RjwXlwdh4z6QYCkvvrPPPyCYKh54TQNybvk6Gwr4bogcvcIdsfVG9e2uMHqttm8DeBSUN9vBZO4SaM2M0xITJ0nihw+JUzAKIyFX2J2Z7qmls3EgNbBy79XqmBNKBkqPRSCZ7YTvLHM38S9rv+Qp0vQ+9+jRg81HTItE/ae40BFk6KREsWmLgxzRDimWiCHRzkMFWgINMhKl+p1y2gDJBC3yDzm3HMC+tdSnlHZw5V3pBOowGL+Fu4+b905+nkviJj9OMBwMufvbyBsSgJxA6awhH0d4rhG8+rnr/N1QI3UEtxVmAWEsmILYYFI6j0mHU5uxWixnEDxaoS8ReQN5vAnPLSPDjmw1FzID0a6z/oySkUYAm2fQ+w7c3QB6a99+VGw+dPC8cnTx51N61guZ5DnjK4CVK7rFXBGwhGvpL0xQYGUn+C1YK6FoJAT88IZBgEV5TsIhYO1gJP4Rk8UE78d23sHWOMACsuexidUEeeEdWpN5HGjpOptZvW1cZrcEaNsLX2jecZx1nnziMQoY0/3aRI3hUdSADn7EahPoenvfpS0VVLNopKfY=
  file: $PACKAGENAME
  on:
    repo: gillesdegottex/pulsemodel
    #tags: true
