language: pyhton

compiler:
    - gcc

os:
    - linux

branches:
    only:
        - master

before_install:
    - echo "before_install..."
    - git submodule update --init --recursive
    - git fetch --tags
    - sleep 1
    - git checkout $TRAVIS_BRANCH
    - export PROJECTGITVERSION=`git describe --tags --always |sed 's/^v//'`
    - echo $PROJECTGITVERSION
    - echo $TRAVIS_OS_NAME
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - export TRAVIS_TAG=`git describe --tags --exact-match HEAD 2>/dev/null`
    - echo $TRAVIS_TAG

install:
    - echo "install..."

script:
    - echo "script..."
    - export PACKAGENAME=pulsemodel_$PROJECTGITVERSION.zip
    - echo "Packaging sources of " $PACKAGENAME
    - pwd
    - ls
    
    - mkdir ../pulsemodel_$PROJECTGITVERSION
    - cp -r * ../pulsemodel_$PROJECTGITVERSION
    - rm -fr ../pulsemodel_$PROJECTGITVERSION/.git*
    - mv ../pulsemodel_$PROJECTGITVERSION .
    - zip -r $PACKAGENAME pulsemodel_$PROJECTGITVERSION
    - ls
    - ls -l $PACKAGENAME
    #- echo $TRAVIS_TAG

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: be+AXEye80z737ul/dSKlTtIg54aKq589nEpw7r//Y+H+2xhEdNx5tBZdD8jmRv9ktk882EKUoxTe90RqUEvGzr21AzUSH69zwhQGOsXdVjsH2rELcPo1gvicyrhLYjHpqDZY9CRin3efjV/A8NFC1GsLiy/7Nb/XYfjSW8UT/WcU2z+0LQC1fWqYbnYQAxrlKt1LDdY1dH3Ra0Vj4y79Brg5CTw/w+vuFaibIDeSzEbqW44LY8mrjJ9hCEn0HpOhY7QO3kwSAKESoBVT4mS2Tpao0OmfAAQ+wl4ZdqgOVRLWGFZGQOelC4GoM0HuBKUiy+TYLW3X8pN2GnA5pv/t+NMjGTsGshpB7kya+Bu8EIH7Lbddq4iXzIYFYmz5HRvtZfHpU3rF9jjQe7UgCDQIXO+8uwBpGjJIQAJBwhyXpWniHiSmWwl9BRwMA6SZVcWScPUzdkwKvVJ9izGrjgBhs1dR6xg0Y6ZTMFRaELqArXBk5RsiRwHrYcNz43njoAsiL+qk/7FThy9/EaBE+YOCcPc2xWEc0EMnEp3Vn6L2y0ITZ/Z5LMN+t6KwCWeU/w/kkl/6pLU3+9JCsdQAJIqQ7bd8PEhuSPdZGe+pR+M+Ls/w3BJuoqG2C5HhtYBXjnod9g3TQwFfBuBJt3pkKi7V0clEUzrjfmjf+m7VIQiZHA=
  file: $PACKAGENAME
  on:
    repo: gillesdegottex/pulsemodel
    #tags: true
