language: pyhton

compiler:
    - gcc

os:
    - linux

branches:
    only:
        - master

before_install:
    - echo "before_install..."
    - git submodule update --init --recursive
    - git fetch --tags
    - sleep 1
    - git checkout $TRAVIS_BRANCH
    - export PROJECTGITVERSION=`git describe --tags --always |sed 's/^v//'`
    - echo $PROJECTGITVERSION
    - echo $TRAVIS_OS_NAME
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - export TRAVIS_TAG=`git describe --tags --exact-match HEAD 2>/dev/null`
    - echo $TRAVIS_TAG

install:
    - echo "install..."

script:
    - echo "script..."
    - export PACKAGENAME=pulsemodel_$PROJECTGITVERSION.zip
    - echo "Packaging sources of " $PACKAGENAME
    - pwd
    - ls
    
    - mkdir ../pulsemodel_$PROJECTGITVERSION
    - cp -r * ../pulsemodel_$PROJECTGITVERSION
    - rm -fr ../pulsemodel_$PROJECTGITVERSION/.git*
    - mv ../pulsemodel_$PROJECTGITVERSION .
    - zip -r $PACKAGENAME pulsemodel_$PROJECTGITVERSION
    - ls
    - ls -l $PACKAGENAME
    #- echo $TRAVIS_TAG

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rPkFQP0EY+p9X+7IlulgVjoWtLwKW4XDzyir9WX6lR/3BsyWAhHcIv3CictT673yKd0N44E2z3c8yzgpQRfT8GHaCxSfTmFBsTkXDp5VNXX7N6W2SX722dE4aU3LEvi0Y6lugiuWSEc1Ock+yJwWre5fdrWZHm27vk66N8C0BdFBS1N9tXoWx05G5TPEI+RbTY00BjNhH6tcLuW9fQUrSsA3IjXk/k7PJFEMwY6w1tbqRZ6caX6KGiibtUZ69GaJeq3FHhlLL/YWzlnJ7ATcz0hCXbskGVcI7QitLzUJ1q6w50vnrI5skXK3xr9CxkkoedVAb/iw/pbeRRyHYbA1tZaeGM9WXrec0AXFCySvPAgxlxpZ4UogCNCg7Typ5jGByUWxgEeG+1LJwTctBB39jMJuYzLCEgtQ7XxZFp7tUjjldILKUbqNJTpf0Ka33dj1O/sulF7ZFe9/tDaJCc/ds8Y7zTa/xPFugtUjy7Q7bN5qoZ/MtfytZrDm/ZCHBQ5NwFEks/yVEvssto4IB937REYnOuVeNHdGs0EUupj2HozRlr01yq+qmtK3I43Wy1GZPKTFUXGGWwQQU9jLaNwDLziZ0kHlhj6aU6qo6ff38R3IaJtU7KcQ0WVc0eIAciu0f5u/3gxQQYlVGIC4wEvu5MSutw95TxlX65zF0e3L/xw=
  file: $PACKAGENAME
  on:
    repo: gillesdegottex/pulsemodel
    #tags: true
